ss6_thuc_hanh_quan_ly_blog_spring_boot
drop DATABASE IF EXISTS ss6_thuc_hanh_quan_ly_blog_spring_boot;
CREATE DATABASE ss6_thuc_hanh_quan_ly_blog_spring_boot;
use ss6_thuc_hanh_quan_ly_blog_spring_boot;
